# Basic Setting
name: rafay_portfolio
description: "Portfolio Website for Abdul Rafay"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'

# Application Dependencies
dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.1.0
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  url_strategy: ^0.2.0
  go_router: ^13.1.0
  url_launcher: ^6.2.4
  font_awesome_flutter: ^10.7.0
  adaptive_navbar: ^0.0.3
  crystal_navigation_bar: ^1.0.0
  iconly: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter Design and Assets
flutter:
  uses-material-design: true
  assets:
        - assets/animation/
        - assets/image/

# Flutter Fonts 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

