# Basic Setting
name: rafay_portfolio
description: "Portfolio Website for Abdul Rafay"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'

# Application Dependencies
dependencies:
  flutter:
    sdk: flutter
  page_transition: ^2.1.0
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  url_strategy: ^0.2.0
  url_launcher: ^6.2.4
  font_awesome_flutter: ^10.7.0
  crystal_navigation_bar: ^1.0.0
  iconly: ^1.0.1
  web_smooth_scroll: ^1.1.0
  flutter_svg: ^2.0.9
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.15.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter Design and Assets
flutter:
  uses-material-design: true
  assets:
        - assets/animation/
        - assets/image/

# App Icons for application
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"

# Flutter Fonts 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

